<?php

namespace App\Services;

use App\Models\StudyMaterial;
use App\Models\MockTest;
use App\Models\Question;
use Illuminate\Support\Str;

class MockTestGenerator
{
    public function generate(StudyMaterial $material, $difficulty = 'medium', $questionCount = 10)
    {
        // 1. Create the Mock Test
        $mockTest = MockTest::create([
            'title' => "Practice: " . $material->title,
            'slug' => Str::slug($material->title . '-' . uniqid()),
            'description' => "Generated mock test based on study material: " . $material->title,
            'difficulty' => $difficulty,
            'study_material_id' => $material->id,
            'is_ai_generated' => true,
            'time_limit' => $questionCount * 1.5, // 1.5 mins per question
        ]);

        // 2. Mock AI Content Analysis & Question Generation
        // In a real app, you would send $material->content to OpenAI/Gemini here.
        $this->generateQuestions($mockTest, $material->content, $difficulty, $questionCount);

        return $mockTest;
    }

    protected function generateQuestions($mockTest, $content, $difficulty, $count)
    {
        // For demonstration, we'll generate high-quality "Simulated AI" questions.
        // We'll try to extract some context from the content if possible.
        
        $topics = ['History', 'Geography', 'Constitution', 'General Knowledge', 'Current Affairs'];
        $verbs = ['What is', 'Who wrote', 'When did', 'Which of the following is', 'Explain'];

        for ($i = 1; $i <= $count; $i++) {
            Question::create([
                'mock_test_id' => $mockTest->id,
                'question_text' => "Analyzing context... [Question $i]: " . $this->getSimulatedQuestion($content, $difficulty),
                'option_a' => "Correct answer based on $difficulty level context",
                'option_b' => "Distractor 1 - Plausible but incorrect",
                'option_c' => "Distractor 2 - Common misconception",
                'option_d' => "Distractor 3 - Irrelevant fact",
                'correct_option' => 'a',
                'explanation' => "This question was generated by analyzing the specific facts related to " . $mockTest->title . " at a $difficulty level.",
                'difficulty' => $difficulty,
            ]);
        }
    }

    protected function getSimulatedQuestion($content, $difficulty)
    {
        // Simple logic to make it look "Analyzed"
        $words = explode(' ', $content);
        $keyword = count($words) > 5 ? $words[rand(0, 4)] : 'Topic';
        
        if ($difficulty == 'hard') {
            return "Based on the critical nuances of $keyword, what is the most significant structural implication?";
        } elseif ($difficulty == 'easy') {
            return "What is the basic definition of $keyword as mentioned in the text?";
        }
        return "How does the text describe the relationship between $keyword and the central theme?";
    }
}
